models/Comentarios.php
<?php

namespace app\models;

use function date_diff;
use DateTime;
use Yii;
use yii\db\Query;
use yii2mod\moderation\enums\Status;

/**
 * This is the model class for table "comments".
 *
 */
class Comentarios extends \yii2mod\comments\models\CommentModel
{
    /**
     * @var Atributo para check de políticas de privacidad.
     */
    public $privacy;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['entity', 'entityId'], 'required'],
            ['content', 'required', 'message' => 'El Comentario no puede estar en blanco'],
            [['content', 'entity', 'relatedTo', 'url'], 'string'],
            ['status', 'default', 'value' => Status::APPROVED],
            ['status', 'in', 'range' => Status::getConstantsByName()],
            ['level', 'default', 'value' => 1],
            ['parentId', 'validateParentID'],
            [['entityId', 'parentId', 'status', 'level'], 'integer'],
            [['privacy'], 'boolean'],
            [
                ['privacy'],
                'required',
                'requiredValue' => 1,
                'message' => 'Debes leer, entender y aceptar las políticas del sitio.'
            ],

            ['content', function($model) {
                $userId = Yii::$app->user->id;
                $ultimoComentario = Comentarios::find()->where([
                    'createdBy' => $userId,
                ])->orderBy(['createdAt' => SORT_DESC])->one();

                if (empty($ultimoComentario)) {
                    return true;
                }

                $ultimoComentario = new DateTime($ultimoComentario->created_at);


                $diferencia = $ultimoComentario->diff(new DateTime('now'));
                $minutos = (new DateTime())->setTimeStamp(0)
                                           ->add($diferencia)
                                           ->getTimeStamp();
                $minutos = (int) ($minutos/60);

                if ($minutos < 5) {
                    $this->addError(
                        $model,
                        'Solo puedes realizar un comentario cada 5 minutos. ' .
                        'Aún te faltan ' . (5-$minutos) . ' minutos.'
                    );
                }

                return true;
            }]
        ];
    }

    /**
     * {@inheritdoc}
     * @return array
     */
    public function attributes()
    {
        return array_merge(parent::attributes(), [
            'privacy' => 'Privacidad',
        ]);
    }

    /**
     * Devuelve la puntuación media para el comentario actual.
     * @return float|int
     */
    public function getPuntos()
    {
        $p = PuntuacionComentarios::find()
            ->select('puntuacion')
            ->where(['comentario_id' => $this->id])
            ->column();

        $total = array_sum($p);
        $votos = count($p);

        if ($votos == 0) {
            return 0;
        }

        return $total / $votos;
    }

    /**
     * Devuelve la puntuación del comentario actual para el usuario logueado.
     * @return int
     */
    public function getMisPuntos()
    {
        $usuario = Yii::$app->user->id;

        $puntuacion = PuntuacionComentarios::find()
            ->select('puntuacion')
            ->where(['comentario_id' => $this->id])
            ->andWhere(['usuario_id' => $usuario])
            ->scalar();

        return $puntuacion ?: 0;
    }

    /**
     * Devuelve el objeto con todos los comentarios junto a su puntuación
     *
     * @return \yii\db\Query
     */
    public static function obtenerPuntuacion()
    {
        $query = new Query();
        $query->from('comment')
            ->leftJoin(
                'puntuacion_comentarios p',
                'p.comentario_id = comment.id'
            )
            ->leftJoin('usuarios u', 'u.id = "createdBy"')
            ->leftJoin('usuarios_datos ud', 'ud.id = u.datos_id');

        return $query;
    }
}

controllers/ComentariosController.php
<?php

namespace app\controllers;

use app\models\Comentarios;

/**
 * ComentariosController extends actions for Comentarios model.
 */
class ComentariosController extends
      \yii2mod\comments\controllers\DefaultController
{

    /**
     * Deletes an existing Comentarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionEliminar($id)
    {
        \Yii::$app->db->createCommand(
            'DELETE FROM comment WHERE "parentId" = ' . $id
        )->execute();

        //Comentarios::deleteAll('"parentId" = ' . $id);

        //$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
}

controllers/TorrentsController.php
<?php

namespace app\controllers;

use app\helpers\Access;
use app\helpers\Amazons3;
use app\helpers\Imageresize;
use app\helpers\Magnet2torrent;
use app\helpers\Roles;
use app\helpers\Security;
use app\models\Comentarios;
use app\models\Comment;
use app\models\Descargas;
use function array_combine;
use function array_map;
use function array_push;
use Bhutanio\BEncode\BEncode;
use DateTime;
use function fclose;
use function fopen;
use function fwrite;
use function implode;
use function isEmpty;
use function json_encode;
use PHP\BitTorrent\Decoder;
use PHP\BitTorrent\Encoder;
use function random_int;
use function sha1;
use function var_dump;
use Yii;
use app\models\Torrents;
use app\models\TorrentsSearch;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Categorias;
use app\models\Licencias;
use yii\web\UploadedFile;
use Devristo\Torrent\Torrent;
use yii2mod\editable\EditableAction;

/**
 * TorrentsController implements the CRUD actions for Torrents model.
 */
class TorrentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'delete', 'update'],
                'rules' => [
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['delete', 'update', 'eliminar'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            $id = Torrents::findOne($_REQUEST['id'])->usuario_id;
                            $isAdmin = Roles::isAdmin();
                            $isAutor = Access::isAutor($id);

                            if ($isAdmin || $isAutor) {
                                return true;
                            }

                            return false;
                        },
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'edit-page' => [
                'class' => EditableAction::className(),
                'modelClass' => Comentarios::className(),
                'forceCreate' => false
            ],
        ];
    }

    /**
     * Lists all Torrents models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TorrentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $query = Categorias::find()->select(['id', 'nombre'])->asArray()
            ->all();

        $categoriasId = [''];
        $categoriasNombres = ['Todas las Categorías'];

        foreach ($query as $ele) {
            array_push($categoriasId, $ele['id']);
            array_push($categoriasNombres, $ele['nombre']);
        }

        $categorias = array_combine($categoriasId, $categoriasNombres);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Displays a single Torrents model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Torrents model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (! Roles::canUpload()) {
            Yii::$app->session->setFlash('error', 'Has subido el límite de torrents diarios para tu rango actual');
            $this->redirect(['torrents/index']);
        }

        $model = new Torrents([
            'usuario_id' => Yii::$app->user->identity->id,
            'scenario' => Torrents::ESCENARIO_CREATE,

        ]);

        // En el caso de existir datos mediante POST los proceso
        if ($model->load(Yii::$app->request->post())) {
            $model->u_torrent = UploadedFile::getInstance($model, 'u_torrent');

            // Es obligatorio que haya un torrent para continuar
            if ($model->u_torrent !== null) {
                $torrent = Torrent::fromFile($model->u_torrent->tempName);
                $pieces = array_map(function($ele) {
                    return sha1($ele, false);
                }, $torrent->getPieces());
                $pieces = implode(',', $pieces);

                $length = [];
                $torrentArray = $torrent->toArray();
                if (!empty($torrentArray['info']['files'])) {
                    $files = $torrentArray['info']['files'];
                    foreach ($files as $file) {
                        $l = $file['length'];
                        array_push($length, $l);
                    }
                }

                $trackers = [];
                foreach ($torrent->getAnnounceList() as $tracker) {
                    array_push($trackers, $tracker[0]);
                }

                $model->n_piezas = $torrent->getNumPieces();
                $model->size_piezas = $torrent->getPieceSize();
                $model->torrentcreate_at = $torrent->getCreationDate()
                                            ->format('Y-m-d H:m:i');
                $model->size = $torrent->getSize(false);
                $model->hash = $torrent->getInfoHash(false);
                $model->archivos = implode(',', $torrent->getFiles());
                $model->archivos_hash = $pieces;
                $model->archivos_size = implode(',', $length);
                $model->trackers = implode(',', $trackers);
                $model->name = $torrent->getName();

                // Guardo imagen si existiera
                $model->u_img = UploadedFile::getInstance($model, 'u_img');
                if ($model->u_img !== null) {
                    $imgObject = new Imageresize($model->u_img);

                    // Subo Imagen a amazon
                    $imagenLocal = $imgObject->getRutaImagen();
                    $nombreAmazon = 'torrentimages/' . $imgObject->getNombre();
                    $amazon = new Amazons3();
                    $amazon->uploadImage(
                        $nombreAmazon,
                        $imagenLocal
                    );

                    $model->imagen = $amazon->getUrlImage($nombreAmazon);
                    $model->u_img = ''; // Deshabilito este atributo temporal.
                }

                if ($model->save()) {
                    //$rol = Yii::$app->user->identity->rol;
                    //$roles = Roles::allRoles();
                    Roles::subirRole();

                    return $this->redirect(['view', 'id' => $model->id]);
                }
            } else {
                Yii::$app->session->setFlash('error',
                                    'Es obligatorio el archivo torrent');
                $model->addError('u_torrent',
                    'Es obligatorio agregar un Torrent válido');
            }
        }

        $licencias = Licencias::getAll();
        $categorias = Categorias::getAll();

        return $this->render('create', [
            'model' => $model,
            'licencias' => $licencias,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Updates an existing Torrents model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $model->scenario = Torrents::ESCENARIO_UPDATE;

        $licencias = Licencias::getAll();
        $categorias = Categorias::getAll();

        return $this->render('update', [
            'model' => $model,
            'licencias' => $licencias,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Convierte el enlace hash del magnet recibido en un archivo torrent
     * @param $hash
     */
    public function actionDescargar($id)
    {
        // Anoto una descarga para el torrent actual.
        $this->actionAnotardescarga($id);

        // Array con toda la información del torrent.
        $info = Magnet2torrent::generateTorrentInfo($id);

        $torrent = new Encoder();
        $torrent = $torrent->encodeDictionary($info);

        $torrentName = trim($info['info']['filename']).'.torrent';
        $rutaSave = 'uploads/'.$torrentName;

        $file = fopen($rutaSave, 'w+');
        $x = fwrite($file, $torrent);
        fclose($file);

        $this->redirect('/'.$rutaSave);
    }

    /**
     * Deletes an existing Torrents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Torrents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.

views/torrents/comentarios/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this \yii\web\View */
/* @var $commentModel \yii2mod\comments\models\CommentModel */
/* @var $encryptedEntity string */
/* @var $formId string comment form id */
?>
<div class="comment-form-container">
    <?php $form = ActiveForm::begin([
        'options' => [
            'id' => $formId,
            'class' => 'comment-box',
        ],
        'action' => Url::to(['/comment/default/create', 'entity' => $encryptedEntity]),
        'validateOnChange' => false,
        'validateOnBlur' => false,
    ]); ?>

    <?= $form->field($commentModel, 'content', ['template' => '{input}{error}'])
        ->textarea(['placeholder' => 'Añadir un comentario', 'rows' => 4,
            'data' => ['comment' => 'content']]) ?>
    <?=$form->field($commentModel, 'parentId', ['template' => '{input}'])
        ->hiddenInput(['data' => ['comment' => 'parent-id']]); ?>
    <div class="comment-box-partial">
        <div class="button-container show">
            <?= Html::a('Pulsa aquí para cancelar sin responder', '#', [
                'id' => 'cancel-reply',
                'class' => 'pull-right',
                'data' => ['action' => 'cancel-reply']
            ]); ?>

            <?= $form->field($commentModel, 'privacy')->checkbox([
                'label' => '',
                'template' => '{input}{beginLabel}{labelTitle}{endLabel}{error}',
            ])->label(
                'Yo acepto las ' . Html::a('Políticas de Privacidad',
                    ['site/politicaprivacidad']) . ' del sitio web.'
            ) ?>

            <?= Html::submitButton('Comentar', [
                    'class' => 'btn btn-primary comment-submit'
            ]); ?>
        </div>
    </div>
    <?php $form->end(); ?>
    <div class="clearfix"></div>
</div>

views/torrents/comentarios/_index.php
<?php

use yii\helpers\ArrayHelper;
use yii\widgets\ListView;
use yii\widgets\Pjax;

/* @var $this \yii\web\View */
/* @var $commentModel \yii2mod\comments\models\CommentModel */
/* @var $maxLevel null|integer comments max level */
/* @var $encryptedEntity string */
/* @var $pjaxContainerId string */
/* @var $formId string comment form id */
/* @var $commentDataProvider \yii\data\ArrayDataProvider */
/* @var $listViewConfig array */
/* @var $commentWrapperId string */
?>

<div class="comment-wrapper" id="<?= $commentWrapperId; ?>">
    <?php Pjax::begin([
        'enablePushState' => false,
        'timeout' => 20000,
        'id' => $pjaxContainerId
    ]); ?>

    <div class="comments row">
        <div class="col-md-12 col-sm-12">
            <div class="title-block clearfix">
                <h3 class="h3-body-title">
                    <?= 'Comentarios ' . $commentModel->getCommentsCount(); ?>
                </h3>
                <div class="title-separator"></div>
            </div>
            <?= ListView::widget(ArrayHelper::merge(
                [
                    'dataProvider' => $commentDataProvider,
                    'layout' => "{items}\n{pager}",
                    'itemView' => '_list',
                    'viewParams' => [
                        'maxLevel' => $maxLevel,
                    ],
                    'options' => [
                        'tag' => 'ol',
                        'class' => 'comments-list',
                    ],
                    'itemOptions' => [
                        'tag' => false,
                    ],
                    //'sorter' => $sort,
                ],
                $listViewConfig

            )); ?>
            <?php if (!Yii::$app->user->isGuest) : ?>
                <?= $this->render('_form', [
                    'commentModel' => $commentModel,
                    'formId' => $formId,
                    'encryptedEntity' => $encryptedEntity,
                ]); ?>
            <?php endif; ?>
        </div>
    </div>
    <?php Pjax::end(); ?>
</div>

views/torrents/comentarios/_list.php
<?php

use app\helpers\Roles;
use yii\helpers\Html;
use yii2mod\editable\Editable;

/* @var $this \yii\web\View */
/* @var $model \yii2mod\comments\models\CommentModel */
/* @var $maxLevel null|integer comments max level */
?>

<li class="comment" id="comment-<?= $model->id; ?>">
    <div class="comment-content" data-comment-content-id="<?= $model->id ?>">
        <div class="comment-author-avatar">
            <?= Html::img($model->getAvatar(), [
                    'alt' => $model->getAuthorName(),
                    'title' => $model->getAuthorName(),
            ]); ?>
        </div>

        <div class="comment-details">
            <div class="comment-action-buttons">
                <?php if (Roles::isAdmin() || ($model->createdBy ==
                        yii::$app->user->id)): ?>
                    <?= Html::a('<span id="eliminarComentario"
                          class="glyphicon glyphicon-trash"></span> Eliminar', [
                        'eliminarcommentario',
                        'id' => $model->id,
                    ], [
                        'data' => [
                            'confirm' => '¿Seguro que quieres eliminar este comentario?',
                            'method' => 'post',
                        ],
                    ]) ?>
                <?php endif; ?>

                <?php if ($model->createdBy != yii::$app->user->id): ?>
                    <span class="btn-reportar-comentario glyphicon
                          glyphicon-bullhorn reportarComentario"
                          data-comment-content-id="<?= $model->id ?>">Reportar</span>
                    <span class="reportarComentario"></span>
                <?php endif; ?>

                <?php if (!Yii::$app->user->isGuest &&
                         ($model->level < $maxLevel || is_null($maxLevel))) : ?>
                    <?= Html::a("<span class='glyphicon glyphicon-share-alt'></span> Responder", '#', ['class' => 'comment-reply', 'data' => ['action' => 'reply', 'comment-id' => $model->id]]); ?>
                <?php endif; ?>
            </div>

            <div class="comment-author-name">
                <span><?= Html::encode($model->getAuthorName()); ?></span>
                <?= Html::a(Html::encode($model->getPostedDate()),
                    Html::encode($model->getAnchorUrl()),
                    ['class' => 'comment-date']); ?>
            </div>

            <div class="comment-body">
                <?php if (Roles::isAdmin() ||
                         ($model->createdBy == yii::$app->user->id)): ?>
                    <?= Editable::widget([
                        'model' => $model,
                        'attribute' => 'content',
                        'url' => '/torrents/edit-page',
                        'options' => [
                            'id' => 'editable-comment-' . $model->id,
                        ],
                    ]); ?>
                <?php else: ?>
                    <?= $model->getContent(); ?>
                <?php endif; ?>
            </div>

            <div class="box-reportes-comentarios">
                <h4>Reportar comentario</h4>

                <div class="form-group">
                    Título:
                    <input type="text"
                           class="reportar-titulo form-control" />
                    <br />
                    Motivo:
                    <input type="text"
                           class="reportar-descripcion form-control" />
                    <br />
                    <div class="box-reportes-comentarios"></div>
                    <div class="btn-enviar-reporte-comentario btn btn-warning">
                        Enviar Reporte
                    </div>
                </div>
            </div>

            <div class="box-votar-comentario"
                 data-mispuntos="<?=$model->misPuntos?>">
                <p>Puntuación total:
                    <span class="puntos"><?=$model->puntos?></span>/10</p>
                <div class="comentarioRating rating" data-rating-max="10"
                      data-comentario="<?=$model->id?>"></div>
            </div>
        </div>
    </div>
</li>
<?php if ($model->hasChildren()) : ?>
    <ul class="children">
        <?php foreach ($model->getChildren() as $children) : ?>
            <li class="comment" id="comment-<?= $children->id; ?>">
                <?= $this->render('_list', ['model' => $children, 'maxLevel'
                => $maxLevel]) ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>