models/Usuarios.php
<?php

namespace app\models;

use DateTime;
use Yii;
use juliardi\captcha\CaptchaValidator;
use yii\helpers\Url;

/**
 * This is the model class for table "usuarios".
 *
 * @property int $id
 * @property int $datos_id
 * @property string $created_at
 * @property string $updated_at
 * @property int $rol_id
 *
 * @property Accesos[] $accesos
 * @property Comentarios[] $comentarios
 * @property Demandas[] $demandas
 * @property PuntuacionComentarios[] $puntuacionComentarios
 * @property Comentarios[] $comentarios0
 * @property PuntuacionTorrents[] $puntuacionTorrents
 * @property Torrents[] $torrents
 * @property ReportesComentarios[] $reportesComentarios
 * @property Comentarios[] $comentarios1
 * @property ReportesTorrents[] $reportesTorrents
 * @property Torrents[] $torrents0
 * @property Torrents[] $torrents1
 * @property Roles $rol
 * @property UsuariosDatos $datos
 */
class Usuarios extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'usuarios';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['datos_id'], 'default', 'value' => null],
            [['rol_id'], 'default', 'value' => 5],
            [['datos_id', 'rol_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['rol_id'], 'exist', 'skipOnError' => true, 'targetClass' => Roles::className(), 'targetAttribute' => ['rol_id' => 'id']],
            [['datos_id'], 'exist', 'skipOnError' => true, 'targetClass' => UsuariosDatos::className(), 'targetAttribute' => ['datos_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'datos_id' => 'Datos',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'rol_id' => 'Rol ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesos()
    {
        return $this->hasMany(Accesos::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios()
    {
        //return $this->hasMany(Comentarios::className(), ['usuario_id' =>'id']);
        return $this->hasMany(Comment::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDemandas()
    {
        return $this->hasMany(Demandas::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPuntuacionComentarios()
    {
        return $this->hasMany(PuntuacionComentarios::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios0()
    {
        return $this->hasMany(Comentarios::className(), ['id' => 'comentario_id'])->viaTable('puntuacion_comentarios', ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPuntuacionTorrents()
    {
        return $this->hasMany(PuntuacionTorrents::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTorrents()
    {
        return $this->hasMany(Torrents::className(), ['id' => 'torrent_id'])->viaTable('puntuacion_torrents', ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportesComentarios()
    {
        return $this->hasMany(ReportesComentarios::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios1()
    {
        return $this->hasMany(Comentarios::className(), ['id' => 'comentario_id'])->viaTable('reportes_comentarios', ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportesTorrents()
    {
        return $this->hasMany(ReportesTorrents::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTorrents0()
    {
        return $this->hasMany(Torrents::className(), ['id' => 'torrent_id'])->viaTable('reportes_torrents', ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTorrents1()
    {
        return $this->hasMany(Torrents::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRol()
    {
        return $this->hasOne(Roles::className(), ['id' => 'rol_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDatos()
    {
        return $this->hasOne(UsuariosDatos::className(), ['id' => 'datos_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuariosBloqueados()
    {
        return $this->hasOne(UsuariosBloqueados::className(), ['usuario_id' => 'id']);
    }

    /**
     * Comprueba si el usuario está bloqueado.
     *
     * @return bool Será true si está bloqueado.
     */
    public function getUsuarioBloqueado()
    {
        return UsuariosBloqueados::findOne([
            'usuario_id' => $this->id,
        ]) ? true : false;
    }

    /**
     * Devuelve el número de torrents para este usuario.
     *
     * @return int|string
     */
    public function getN_torrents()
    {
        $usuario = Yii::$app->user->id;

        return Torrents::find()->where([
            'usuario_id' => $this->id,
        ])->count();
    }

    /**
     * Obtiene los usuarios creados en total devolviendo el año en el que se
     * han creado y la cantidad de usuarios para ese año.
     * Será devuelto en un array.
     *
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function creadosEntotal()
    {
        return Usuarios::find()
            ->select(['EXTRACT(YEAR FROM created_at) as year, count(*) as cantidad'])
            ->groupBy('year')
            ->orderBy('year ASC')
            ->asArray()
            ->all();
    }

    /**
     * Obtiene los usuarios creados este mismo mes y los devuelve como array
     * por día de registro y cantidad para es cada día.
     *
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function creadosEsteMes()
    {
        $date = new DateTime('now');
        $year = $date->format('Y');
        $mes = $date->format('m');
        $date = $date->setDate($year, $mes, 1)
                ->setTime(0, 0)
                ->format('Y-m-d H:i:s');

        return Usuarios::find()
            ->select(['date(created_at) as date, count(*) as cantidad'])
            ->where(['>=', 'created_at', $date])
            ->groupBy('date')
            ->orderBy('date ASC')
            ->asArray()
            ->all();
    }
}

controllers/UsuariosController.php
<?php

namespace app\controllers;

use app\helpers\Access;
use app\helpers\Roles;
use app\models\Comment;
use app\models\Preferencias;
use app\models\Torrents;
use app\models\UsuariosDatos;
use function var_dump;
use Yii;
use app\models\Usuarios;
use app\models\UsuariosSearch;
use yii\db\Expression;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UsuariosController implements the CRUD actions for Usuarios model.
 */
class UsuariosController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'delete', 'update', 'aprobar'],
                'rules' => [
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                    [
                        'actions' => ['delete', 'update'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            $isAdmin = Roles::isAdmin();
                            $isAutor = Access::isAutor($_REQUEST['id']);

                            if ($isAdmin || $isAutor) {
                                return true;
                            }

                            return false;
                        },
                        'roles' => ['@'],
                    ],

                    [
                        'actions' => ['aprobar'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            $isAdmin = Roles::isAdmin();

                            if ($isAdmin) {
                                return true;
                            }

                            return false;
                        },
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Usuarios models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsuariosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Usuarios model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Crea un nuevo usuario a partir del modelo.
     * Si consigue crearse correctamente, se redirigirá a la vista del usuario
     * recién creado.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        if (Access::ipBloqueada()) {
            Yii::$app->getResponse()
                ->redirect(['site/iplocked'])
                ->send();
        }

        $model = new UsuariosDatos([
            'scenario' => UsuariosDatos::ESCENARIO_CREATE,
            'lastlogin_at' => new Expression('NOW()'),
            'privacy' => false,
        ]);

        $isPOST = $model->load(Yii::$app->request->post());

        if ($isPOST && $model->save()) {
            $usuario_id = Usuarios::findOne($model->id);
            $usuario_id->datos_id = $model->id;
            $usuario_id->update();

            if (! Roles::isAdmin()) {
                Yii::$app->user->login($model);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Usuarios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = UsuariosDatos::findOne($id);
        $model->password = '';
        $model->scenario = UsuariosDatos::ESCENARIO_UPDATE;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Usuarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $isAdmin = Roles::isAdmin();

        $user = Usuarios::findOne($id);
        $user->datos_id = 2;
        $user->update();

        UsuariosDatos::findOne($id)->delete();

        if ($isAdmin) {
            return $this->redirect(['usuarios/index']);
        }

        Yii::$app->user->logout();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Usuarios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Usuarios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Usuarios::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Aprueba a un determinado usuario en la plataforma subiéndole
     * manualmente el rango.
     * @param $id El id del usuario al que subir el rango.
     *
     * @return \yii\web\Response
     */
    public function actionAprobar($id)
    {
        $model = Usuarios::findOne($id);

        $model->rol_id = 6;
        $model->save();

        return $this->redirect(['index']);
    }
}

views/usuarios/_avatares.php
<?php
/**
 * @author Raúl Caro Pastorino
 * @link https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license https://www.gnu.org/licenses/gpl-3.0-standalone.html
**/

$avatares = [
    [
        'nombre' => 'default.png',
        'titulo' => 'Imagen de Avatar por defecto'
    ],
    [
        'nombre' => 'hippy.png',
        'titulo' => 'Imagen de Avatar hippy'
    ],
    [
        'nombre' => 'rey.png',
        'titulo' => 'Imagen de Avatar rey'
    ],
    [
        'nombre' => 'rockero.png',
        'titulo' => 'Imagen de Avatar rockero'
    ],
];
?>

<?php foreach($avatares as $av): ?>
    <div class="col-xs-3 col">
        <img src="/images/user-avatar/<?= $av['nombre'] ?>"
             data-name="<?= $av['nombre'] ?>"
             alt="<?= $av['titulo'] ?>"
             title="<?= $av['titulo'] ?>" />
    </div>
<?php endforeach ?>

<div class="modal fade box-avatares-modal"
     tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-header">
            <h3 class="modal-title" id="exampleModalLongTitle">
                Seleccionar Avatar
            </h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

            <div class="row">
                <div class="col-sm-12">
                    <button type="button"
                            class="btn-aceptar btn btn-success center-block"
                            data-dismiss="modal">
                        Aceptar
                    </button>
                </div>
            </div>
        </div>
        <div class="modal-content">
            <?php require_once '_avataresAll.php'; ?>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <button type="button"
                        class="btn-aceptar btn btn-success center-block"
                        data-dismiss="modal">
                    Aceptar
                </button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <button type="button" class="btn-modal btn btn-primary center-block"
                data-toggle="modal"
                data-target=".box-avatares-modal">Mostrar más Avatares</button>
    </div>
</div>

views/usuarios/_avataresAll.php
<?php
/**
 * Almaceno todas las imágenes en el array.
 */
$avataresTodos = [];
$dir = dir('images/user-avatar');
while (($archivo = $dir->read()) !== false) {
    if (preg_match("/png$/i", $archivo)){
        array_push($avataresTodos, [
            'nombre' => $archivo,
            'titulo' => basename($archivo, '.png'),
        ]);
    }
}
$dir->close();
?>

<?php foreach($avataresTodos as $av): ?>
    <div class="avatar-modal col-xs-4 col">
        <img src="/images/user-avatar/<?= $av['nombre'] ?>"
             data-name="<?= $av['nombre'] ?>"
             alt="<?= $av['titulo'] ?>"
             title="<?= $av['titulo'] ?>" />
    </div>
<?php endforeach ?>

views/usuarios/_search.php
<?php

use app\helpers\Roles;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsuariosSearch */
/* @var $form yii\widgets\ActiveForm */

// Variables
$isAdmin = Roles::isAdmin();
?>

<div id="box-form-search"
     class="text-center usuarios-search container center-block">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'id' => 'form-search-users-index',
    ]); ?>

    <?php if ($isAdmin): ?>
        <?php $sizerow = '4' ?>
        <div class="row col-sm-<?=$sizerow?> center-block">
            <?= $form->field($model, 'email') ?>
        </div>

        <div class="row col-sm-<?=$sizerow?> center-block">
            <?= $form->field($model, 'id') ?>
        </div>

        <!-- IP -->
        <!-- ROL -->
    <?php else: ?>
        <?php $sizerow = '12' ?>
    <?php endif ?>

    <div class="row col-sm-<?=$sizerow?> center-block">
        <?= $form->field($model, 'nick') ?>
    </div>
</div>

<div id="box-form-button-search" class="container col-sm-12 center-block">
    <?php if ($isAdmin): ?>
        <?php $sizerow = '4' ?>
        <div class="col-sm-<?=$sizerow?> text-center center-block">
            <?= Html::a('Crear Usuario', ['usuarios/create'], [
                'class' => 'btn btn-success',
            ]); ?>
        </div>
    <?php else: ?>
        <?php $sizerow = '6' ?>
    <?php endif ?>

    <div class="col-sm-<?=$sizerow?> text-center center-block">
        <?= Html::submitButton(Yii::t('forms', 'search'), [
            'class' => 'btn btn-primary'
        ]) ?>
    </div>

    <div class="col-sm-<?=$sizerow?> text-center center-block">
        <?= Html::button(Yii::t('forms', 'clear'), [
            'id' => 'form-btn-clear',
            'class' => 'btn btn-danger',
        ]) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

views/usuarios/create.php
<?php

/**
 * @author Raúl Caro Pastorino
 * @link https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

use app\assets\UsuariosCreateAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */

// Registro assets para esta vista
UsuariosCreateAsset::register($this);

$this->title = Yii::t('usuarios-create', 'title');
$this->params['breadcrumbs'][] = [
    'label' => Yii::t('usuarios-create', 'breadcrumbs'),
    'url' => ['index']
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="usuarios-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/usuarios/index.php
<?php

/**
 * @author Raúl Caro Pastorino
 * @link https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

use app\assets\UsuariosIndexAsset;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use app\helpers\Roles;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuariosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Usuarios';
$this->params['breadcrumbs'][] = $this->title;

// Registro assets para esta vista
UsuariosIndexAsset::register($this);

// Variables
$isAdmin = Roles::isAdmin();

$redesSociales = [
    'label' => '',
    'format' => 'raw',
    'value' => function($model) {
        $web = Html::encode($model->datos->web);
        $facebook = 'https://facebook.com/' .
            Html::encode($model->datos->facebook);
        $twitter = 'https://twitter.com/' .
            Html::encode($model->datos->twitter);
        $gplus = 'https://plus.google.com/' .
            Html::encode($model->datos->googleplus);
        $dir_iconos = yii::getAlias('@r_iconos');

        $imgs = '<a href="'.$facebook.'" class="user-social">';
        $imgs .= '<img src="/'.$dir_iconos.'/facebook.png"/></a>';

        $imgs .= '<a href="'.$twitter.'" class="user-social">';
        $imgs .= '<img src="/'.$dir_iconos.'/twitter.png"/></a>';

        $imgs .= '<a href="'.$gplus.'" class="user-social">';
        $imgs .= '<img src="/'.$dir_iconos.'/gplus.png"/></a>';

        return $imgs;
    }
];

$columns = [
    [
        'format' => 'raw',
        'value' => function($model) {
            $nombre = $model->datos->avatar;
            $ruta = yii::getAlias('@r_avatar');
            $imagen = $ruta.'/'.$nombre;

            if (empty($nombre) || (! file_exists($imagen))) {
                $imagen = $ruta.'/'.'default.png';
            }
            return '<img src="/'.$imagen.'" />';
        }
    ],
    [
        'label' => 'Nick',
        'format' => 'raw',
        'value' => function($model) {
            return Html::a(Html::encode($model->datos->nick), [
                Url::to('usuarios/view'),
                'id' => $model->id
            ]);
        }
    ],
    'datos.biografia',
    [
        'attribute' => 'datos.web',
        'format' => 'raw',
        'value' => function($model) {
            return Html::a(Html::encode($model->datos->web),
                Html::encode($model->datos->web),
                [
                    'class' => 'btn'
                ]);
        }
    ],
    $redesSociales,
];

$columnsAdmin = [
    'id',
    [
        'label' => 'Nombre',
        'format' => 'raw',
        'value' => function($model) {
            return Html::a(Html::encode($model->datos->nombre), [
                Url::to('usuarios/view'),
                'id' => $model->id
            ]);
        }
    ],
    'rol.tipo:text:Rol',  // Tipo de rol
    'datos.email:email',
    'datos.lastlogin_at:datetime',
    [
        'attribute' => '',
        'format' => 'raw',
        'value' => function($model) {
            $buttons = '';
            if (isset($model->usuariosBloqueados->usuario)) {
                $buttons .=  Html::a('Desbloquear', [
                    Url::to('usuarios-bloqueados/desbloquear'),
                    'id' => $model->usuariosBloqueados->id
                ],
                    [
                        'class' => 'btn btn-warning btn-admin',
                        'data' => [
                            'method' => 'post',
                        ],
                    ]
                );
            } else {
                $buttons .=  Html::a('Bloquear', [
                    Url::to('usuarios-bloqueados/bloquear'),
                    'id' => $model->id,
                ],
                    [
                        'class' => 'btn btn-danger btn-admin',
                    ]
                );
            }
            $buttons .=  Html::a('Ver', [
                Url::to('usuarios/view'),
                'id' => $model->id,
            ],
                [
                    'class' => 'btn btn-success btn-admin',
                ]
            );
            if ($model->rol->tipo == 'tmp') {
                $buttons .=  Html::a('Aprobar', [
                    Url::to('usuarios/aprobar'),
                    'id' => $model->id
                ],
                    [
                        'class' => 'btn btn-warning btn-admin',
                        'data' => [
                            'method' => 'post',
                        ],
                    ]
                );
            }
            $buttons .=  Html::a('Modificar', [
                Url::to('usuarios/update'),
                'id' => $model->id,
            ],
                [
                    'class' => 'btn btn-primary btn-admin',
                ]
            );
            $buttons .=  Html::a('Eliminar', [
                Url::to('usuarios/delete'),
                'id' => $model->id,
            ],
                [
                    'class' => 'btn btn-danger btn-admin',
                    'data' => [
                        'confirm' => '¿Estás seguro que quieres eliminar el usuario?',
                        'method' => 'post',
                    ],
                ]
            );

            return $buttons;
        }
    ],
];

if ($isAdmin) {
    foreach ($columnsAdmin as $col) {
        array_push($columns, $col);
    }
}
?>

<div class="usuarios-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'class' => 'grid-view',
        'tableOptions' => [
            'class' => 'tablaUsuariosIndex'
        ],
        'filterRowOptions' => [
            'class' => 'trSearch'
        ],
        'columns' => $columns,
    ]); ?>
</div>

views/usuarios/update.php
<?php

/**
 * @author Raúl Caro Pastorino
 * @link https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

use app\assets\UsuariosCreateAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */

$this->title = 'Actualizar Usuario:' . Html::encode($model->nick);
$this->params['breadcrumbs'][] = ['label' => 'Usuarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Html::encode($model->nick),
    'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Modificar Usuario';

// Registro assets para esta vista
UsuariosCreateAsset::register($this);
?>

<div class="usuarios-update">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>