controllers/SiteController.php
<?php

namespace app\controllers;

use app\helpers\Access;
use app\models\Accesos;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (Access::ipBloqueada()) {
            Yii::$app->getResponse()
                ->redirect(['site/iplocked'])
                ->send();
        }

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        // Cargo datos y registro si el login es correcto o no lo es
        if ($model->load(Yii::$app->request->post())) {
            if($model->login()) {
                Access::registrarAcceso();
                return $this->goBack();
            } else {
                Access::registrarErrorAcceso();
            }
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays userlocked page.
     *
     * @return string
     */
    public function actionUserlocked()
    {
        return $this->render('userlocked');
    }

    /**
     * Displays iplocked page.
     *
     * @return string
     */
    public function actionIplocked()
    {
        return $this->render('iplocked');
    }

    /*
     * Displaus avisolegal page.
     *
     * @return string
     */
    public function actionAvisolegal()
    {
        return $this->render('avisolegal');
    }

    /**
     * Displays politicacookies page.
     *
     * @return string
     */
    public function actionPoliticacookies()
    {
        return $this->render('politicacookies');
    }

    /**
     * Displays politicaprivacidad page.
     *
     * @return string
     */
    public function actionPoliticaprivacidad()
    {
        return $this->render('politicaprivacidad');
    }

    /**
     * Displays Social Networks page.
     *
     * @return string
     */
    public function actionSocial()
    {
        return $this->render('redessociales');
    }
    public function actionEstadisticas()
    {
        return $this->render('administrar/estadisticas');
    }
}

views/site/_slide-index.php
<?php
$slideImg = [
    [
        'active' => true,
        'src' => 'slide/slide1.jpg',
        'title' => 'Torrent Libre',
    ],
    /*
    [
        'src' => 'slide/slide2.jpg',
        'title' => 'Máquinas Virtuales',
    ],
    [
        'src' => 'slide/slide3.jpg',
        'title' => 'Libros',
    ],
    [
        'src' => 'slide/slide4.jpg',
        'title' => 'Subir Torrent',
    ],
    [
        'src' => 'slide/slide5.jpg',
        'title' => 'Buscar Torrent',
    ],
    */
];?>

<?= \aki\imageslider\ImageSlider::widget([
    'baseUrl' => Yii::getAlias('@web/images'),
    'nextPerv' => true,
    'indicators' => false,
    'classes' => 'img-rounded',
    'images' => $slideImg,
]); ?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/avisolegal.php
<?php
/**
 * Created by PhpStorm.
 * User: fryntiz
 * Date: 23/10/18
 * Time: 15:05
 */
/**
 * @author    Raúl Caro Pastorino
 * @link      https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Aviso Legal';

?>
<div class="site-avisolegal container">
    <h1>Aviso Legal sobre <span>TorrentLibre</span></h1>

    <div class="nav navbar-link">
        <ul>
            <li><?= Html::a('Política de Cookies', ['site/politicacookies'])
                ?></li>
            <li><?= Html::a('Política de Privacidad',
                    ['site/politicaprivacidad']) ?></li>
        </ul>
    </div>

    <section class="row col-sm-12">
        <h2>Titularidad</h2>
        <div class="box-content-white">
            <p>
                Se informa a los usuarios de la presente página web, en adelante Usuario, que el titular del website https://torrentlibre.laguialinux.es y su versión en desarrollo https://torrentlibre.herokuapp.com, en adelante Sitio Web, es Raúl Caro Pastorino.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Condiciones de Uso</h2>
        <div class="box-content-white">
            <p>
                Si el usuario se suscribe a cualquier servicio del Sitio Web lo hará aceptando las Condiciones de Uso y Política de Privacidad y Cookies que se le mostrarán.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Veracidad de los datos</h2>
        <div class="box-content-white">
            <p>
                El Usuario reconoce que los datos suministrados son veraces y ciertos, comprometiéndose a notificar cualquier cambio o modificación que se produzca en los mismos.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Modificación del servicio</h2>
        <div class="box-content-white">
            <p>
                El Sitio Web se reserva el derecho de modificar o eliminar los servicios que ofrece a través de la web sin ninguna garantía por pérdida de datos o disconformidad.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Normas generales de uso</h2>
        <div class="box-content-white">
            <p>
                El Usuario se obliga a utilizar este Sitio Web de forma diligente, correcta y respetuosa, en especial cuando publique opiniones y/o comentarios.
            </p>

            <p>
                Asimismo, se obliga a título meramente enunciativo a no realizar comentarios o acciones:
            </p>

            <ul>
                <li>
                    Difamatorios, inexactos, falsos, abusivos, injuriosos,
                    obscenos, irreverentes, ofensivos, insultantes, tácita o expresamente sexuales, amenazantes, acosadores, racistas, sexistas, discriminatorios por cualquier motivo, que atenten contra la moral, el orden público, los derechos fundamentales, las libertas públicas, el honor, la intimidad o la imagen de terceros y en general la normativa vigente, y/o ilegales o infractores de derechos de terceros (por ejemplo, p.e., derechos de propiedad industrial e intelectual; derechos de privacidad o publicidad).
                </li>
                <li>
                    Transmisores de correo basura, “SPAM”, mensajes con fines comerciales, “cartas en cadena” o mailings masivos no solicitados, falsos, engañosos o promuevan actividades ilegales o conducta grosera, amenazante, obscena, difamatoria o injuriosa.
                </li>
                <li>
                    Que suministren información práctica sobre actividades ilegales.
                </li>
                <li>
                    Que conlleven cualquier actividad comercial, publicidad o ventas, incluso aunque no haya contraprestación monetaria.
                </li>
                <li>
                    Que contengan datos de carácter personal sobre terceras personas que requieran el consentimiento del propietario o titular de los derechos.
                </li>
                <li>
                    El Usuario responderá frente al Sitio Web o frente a cualquier tercero, de cualesquiera daños y perjuicios que pudieran causarse como consecuencia del incumplimiento de dicha obligación. EL Sitio Web no interviene los contenidos de los Usuarios.
                </li>
            </ul>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Propiedad intelectual</h2>
        <div class="box-content-white">
            <p>
                Mediante estas condiciones legales no se cede ningún derecho
                de propiedad intelectual o industrial sobre este Sitio Web y
                sus contenidos (fotografías, vídeos, creaciones, textos,...)
                para fines comerciales y/o en plataformas lucrativas o con
                ánimo de lucro. Debiéndose siempre respetar las licencias
                correspondientes.
            </p>

            <p>
                El código fuente en https://github.com/fryntiz/torrentlibre tiene licencia GPLv3 y el contenido general del sitio web se establece en Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) https://creativecommons.org/licenses/by-nc/4.0/
            </p>

            <p>
                Cada usuario puede establecer una licencia propia por su material subido cediendo el permiso de uso al Sitio Web, al no declarar licencia se aplciará CC BY-NC 4.0 al igual que el resto del Sitio Web.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Obligaciones del Sitio Web</h2>
        <div class="box-content-white">
            <p>
                El Sitio Web es responsable de los servicios que presta por ella misma y de los contenidos directamente originados por la propia web e identificados con su correspondiente copyright.
            </p>

            <p>
                El Sitio Web adoptará las medidas necesarias que permitan garantizar la seguridad y privacidad en las comunicaciones.
            </p>

            <p>
                El Sitio Web se reserva el derecho a suspender temporalmente la prestación del servicio sin previo aviso al Usuario, siempre y cuando sea necesario para efectuar operaciones de mantenimiento, actualización o mejora del servicio.
            </p>

            <P>
                El Sitio Web no puede asegurar la disponibilidad y continuidad permanente del servicio web debido a interrupciones, ataques, mantenimiento, errores, fallos etc..
            </p>
        </div>
    </section>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p style="background-color: #fff; padding: 10px 5px">
        Ha ocurrido un error buscando la página que has solicitado.
        <br />
        Si crees que hay algún problema en el sitio web contáctanos para
        solucionarlo.
    </p>
</div>

views/site/iplocked.php
<?php
/**
 * Created by PhpStorm.
 * User: fryntiz
 * Date: 21/10/18
 * Time: 17:22
 */

use app\assets\IpLockedAsset;

/**
 * @author    Raúl Caro Pastorino
 * @link      https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

/* @var $this yii\web\View */

IpLockedAsset::register($this);

$this->title = 'IP Bloqueada';

?>
<div id="site-iplocked">
    <h1>IP Bloqueada</h1>
    <h2>Sitio temporal con el desarrollo</h2>

    <p>
        La IP desde la que intentas acceder ha sido bloqueada por demasiados
        intentos de conexión fallidos consecutivos.
    </p>

    <p class="alert-warning">
        Para cualquier consulta al respecto diríjase por favor a <?=
        Yii::getAlias('@adminEmail') ?>
    </p>
</div>

views/site/politicacookies.php
<?php
/**
 * Created by PhpStorm.
 * User: fryntiz
 * Date: 23/10/18
 * Time: 15:05
 */
/**
 * @author    Raúl Caro Pastorino
 * @link      https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Aviso Legal';

?>
<div class="site-avisolegal container">
    <h1>Políticas de Cookies <span>TorrentLibre</span></h1>

    <div class="nav navbar-link">
        <ul>
            <li><?= Html::a('Aviso Legal', ['site/avisolegal']) ?></li>
            <li><?= Html::a('Política de Privacidad',
                    ['site/politicaprivacidad']) ?></li>
        </ul>
    </div>

    <section class="row col-sm-12">
        <h2>POLÍTICA DE COOKIES</h2>
        <div class="box-content-white">
            <p>
                Deseamos informarte que Sitio Web utiliza cookies para medir y analizar la navegación de nuestros usuarios.
            </p>

            <p>
                Las cookies son unos archivos que se instalan en el equipo desde el que accedes a Sitio Web con las finalidades que se describen en esta página.
            </p>

            <p>
                Las aplicaciones que utilizamos para obtener información de la navegación, medir y analizar la audiencia son:
                <ul>
                    <li>Google Analytics http://www.google.com/policies/technologies/cookies/</li>
                </ul>
            </p>

            <p>
                Estas aplicaciones han sido desarrolladas por Google que nos prestan el servicio de medición y análisis de la audiencia de nuestras páginas. Asimismo ellas mismas pueden utilizar estos datos para mejorar sus propios servicios y para ofrecer servicios a otras empresas. Puedes conocer esos otros usos desde los enlaces indicados.
            </p>

            <p>
                Estas herramientas no obtienen datos sobre tu nombre o apellidos ni de la dirección postal desde donde te conectas. La información que obtienen está relacionada con el número de páginas visitas, el idioma, red social en la que se publican nuestras noticias, la ciudad a la que está asignada la dirección IP desde la que accedes, el número de nuevos usuarios, la frecuencia y reincidencia de las visitas, el tiempo de visita, el navegador y el operador o tipo de terminal desde el que se realiza la visita.
            </p>

            <p>
                Esta información la utilizamos para mejorar nuestras páginas, detectar nuevas necesidades y valorar las mejoras a introducir con la finalidad de prestar un mejor servicio a los usuarios que nos visitan adaptándolas por ejemplo a los navegadores o terminales más utilizados.
            </p>

            <p>
                Para permitir, conocer, bloquear o eliminar las cookies instaladas en tu equipo puedes hacerlo mediante la configuración de las opciones del navegador instalado en tu ordenador.
                Puedes encontrar información sobre cómo hacerlo en el caso que uses como navegador:
                <ul>
                    <li>
                        Firefox https://support.mozilla.org/es/kb/cookies-informacion-que-los-sitios-web-guardan-en-?esab=a&s=politic+cookies&r=0&as=s
                    </li>

                    <li>
                        Chrome https://support.google.com/chrome/bin/answer.py?hl=es&answer=95647
                    </li>

                    <li>
                        Explorer https://support.microsoft.com/es-es/help/278835/how-to-delete-cookie-files-in-internet-explorer
                    </li>

                    <li>
                        Edge https://privacy.microsoft.com/es-es/windows-10-microsoft-edge-and-privacy
                    </li>

                    <li>
                        Safari https://support.apple.com/kb/PH21411?viewlocale=es_ES&locale=es_ES
                    </li>
                </ul>
            </p>
        </div>
    </section>
</div>

views/site/politicaprivacidad.php
<?php
/**
 * Created by PhpStorm.
 * User: fryntiz
 * Date: 23/10/18
 * Time: 15:05
 */
/**
 * @author    Raúl Caro Pastorino
 * @link      https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Aviso Legal';

?>
<div class="site-avisolegal container">
    <h1>Políticas de Privacidad en <span>TorrentLibre</span></h1>

    <div class="nav navbar-link">
        <ul>
            <li><?= Html::a('Aviso Legal', ['site/avisolegal']) ?></li>
            <li><?= Html::a('Política de Cookies', ['site/politicacookies']) ?></li>
        </ul>
    </div>

    <section class="row col-sm-12">
        <h2>POLÍTICA DE PRIVACIDAD</h2>
        <div class="box-content-white">
            <p>
                Hasta ahora se venía cumpliendo la LOPD para temas de privacidad de datos, ley que a partir del 25 de Mayo del 2018 queda sustituida por el Reglamento General de Protección de datos (RGPD) de la Unión Europea.
            </p>

            <p>
                La presente Política de Privacidad será válida únicamente para los datos de carácter personal obtenidos en el Sitio Web, no siendo aplicable para aquella información recabada por terceros en otras páginas web, incluso si éstas se encuentran enlazadas por el Sitio Web.
            </p>

            <p>
                Con ello este Sitio Web manifiesta su compromiso por mantener y garantizar las relaciones comerciales con el Usuario de forma segura mediante la protección de sus datos personales y garantizando su derecho a la privacidad.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Datos Personales</h2>
        <div class="box-content-white">
            <p>
                Datos personales que requiere en el Sitio Web
                Para poder prestar nuestros servicios necesitamos algunos datos identificativos según el servicio que Sitio Web te preste:
            </p>
        </div>

        <div class="box-content-white">
            <h3>Para los comentarios</h3>
            <ul>
                <li>
                    Nombre → para identificar al Usuario.
                </li>

                <li>
                    Email → para conocer el email desde el que se ha hecho el
                    comentario.
                </li>
            </ul>
        </div>

        <div class="box-content-white">
            <h3>Para el área privada de clientes</h3>
            <p>
                El área de clientes se trata de una zona privada. El responsable del Sitio Web te proporcionará un usuario y contraseña para que como Usuario puedas acceder a este servicio restringido, entendiendo que aceptas todas las condiciones legales.
            </p>
        </div>

        <div class="box-content-white">
            <h3>Para el formulario de contacto</h3>
            <ul>
                <li>Nombre y apellidos → para poder responder a la consulta.</li>
                <li>Email → para poder responder a la consulta.</li>
            </ul>
        </div>

        <div class="box-content-white">
            <p>
                Adicionalmente, cuando visitas nuestro Sitio Web determinada información se almacena automáticamente por motivos técnicos como la dirección IP asignada por tu proveedor de acceso a Internet.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Legitimación</h2>
        <div class="box-content-white">
            <p>
                Gracias al consentimiento podemos tratar tus datos, siendo este un requisito obligatorio para que puedas acceder de forma correcta a los servicios del Sitio Web.
            </p>

            <p>
                El usuario dispone de su derecho al olvido cuando quiera que todos sus datos sean eliminados de nuestras base de datos.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Categoría de los datos</h2>
        <div class="box-content-white">
            <p>
                Los datos que recopila Sitio Web no son considerados datos sensibles o protegidos.
            </p>
            
            <p>
                Según el artículo 9.1 del nuevo reglamento general de protección de datos de la unión europea (RGPD) se consideran datos sensibles o protegidos los datos personales que revelen:
            </p>

            <ul>
                <li>El origen étnico o racial.</li>
                <li>Las opiniones políticas.</li>
                <li>Las convicciones religiosas o filosóficas.</li>
                <li>La afiliación sindical.</li>
                <li>El tratamiento de datos genéticos.</li>
                <li>Datos biométricos dirigidos a identificar de manera unívoca a una persona física.</li>
                <li>Datos relativos a la salud.</li>
                <li>Datos relativos a la vida sexual o las orientación sexuales de una persona física.</li>
            </ul>

            <p>
                Sólo trabajamos con los datos mínimos identificativos para llevar a cabo nuestra labor: nombre, apellidos, nick y email.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Tiempo de conservación de los datos</h2>
        <div class="box-content-white">
            <p>
                Los datos del cliente: nombre, correo electrónico, etc. permanecerán en nuestro sistema lo que legalmente y técnicamente se requiera para la operativa normal del Sitio Web, a menos que el Usuario ejerza su derecho a su eliminación o actualización.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Normativa de aplicación</h2>
        <div class="box-content-white">
            <p>
                Desde el el 25 de mayo de 2018, el Sitio Web se rige por el Reglamento General sobre Protección de Datos (RGPD) de la Unión Europea.

                <br />

                <a href="https://www.boe.es/doue/2016/119/L00001-00088.pdf"
                   alt="Reglamento General sobre Protección de Datos (RGPD)">
                    https://www.boe.es/doue/2016/119/L00001-00088.pdf
                </a>
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Medidas de seguridad</h2>
        <div class="box-content-white">
            <p>
                Este Sitio Web está alojado en los sistemas operados por Heroku (Desarrollo), Acens y Aruba.it para producción, en adelante Servidores, están implantadas las medidas de seguridad técnicas y organizativas necesarias para garantizar la seguridad de los datos de carácter personal del Usuario y evitar así su alteración, pérdida y tratamiento y/o acceso no autorizado. Esto habida cuenta del estado de la tecnología, la naturaleza de los datos almacenados y los riesgos a que están expuestos, ya provengan de la acción humana o del medio físico o natural. Todo ello de conformidad con lo previsto en el RGPD.
            </p>

            <p>
                Asimismo, en los Servidores se han establecido medidas adicionales en orden a reforzar la confidencialidad e integridad de la información en este Sitio Web. Manteniendo continuamente la supervisión, control y evaluación de los procesos para asegurar el respeto a la privacidad de los datos.
            </p>

            <p>
                Concretamente, las medidas que se adoptan en las empresas de hosting/vps son:
            </p>

            <ul>
                <li>Conexión con certificado SSL en el Sitio Web.</li>
                <li>Encriptación de las claves y contraseñas utilizando algoritmos criptográficos estándar.</li>
                <li>Protección de los servidores mediante cortafuegos, aislamiento de procesos, y otras medidas de seguridad estándar.</li>
                <li>Copias de seguridad periódicas distribuidas geográficamente para garantizar la continuidad del servicio en caso de incidente.</li>
            </ul>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Ejercicios de derechos</h2>
        <div class="box-content-white">
            <p>
                Aquel Usuario que haya facilitado sus datos al Sitio Web, podrá dirigirse al titular de la web con el fin de poder ejercitar gratuitamente su derecho de acceso a sus datos, rectificación o supresión, limitación y oposición respecto de los datos incorporados en sus ficheros.
            </p>

            <p>
                El método que debe utilizar el Usuario para comunicarse con el Sitio Web será mediante su cuenta de email registrada en nuestro servicio web, o por escrito.
            </p>

            <p>
                El Usuario podrá ejercitar sus derechos mediante comunicación
                por escrito dirigida al Sitio Web con la referencia
                "Protección de datos", especificando sus datos, acreditando
                su identidad y los motivos de su solicitud en la siguiente
                dirección:
                <a href="mailto:webtorrentlibre@gmail.com"
                   alt="webtorrentlibre@gmail.com">
                    webtorrentlibre@gmail.com
                </a>
            </p>

            <p>
                Cualquier información que necesitemos almacenar en virtud de una obligación legal, fiscal o contractual, será bloqueada y sólo utilizada para dichos fines en lugar de ser borrada.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Modificación de la política de privacidad</h2>
        <div class="box-content-white">
            <p>
                El Sitio Web se reserva el derecho de modificar la Política de Privacidad, motivado por un cambio legislativo, jurisprudencial o doctrinal de la Agencia Española de Protección de Datos.
            </p>

            <p>
                Cualquier modificación de la Política de Privacidad será publicada al menos diez días antes de su efectiva aplicación.
            </p>

            <p>
                Responsable del fichero y encargado del tratamiento
                El responsable del fichero de datos es el titular del Sitio Web.
            </p>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Servicios ofrecidos por terceros</h2>
        <div class="box-content-white">
            <p>
                Para prestar servicios estrictamente necesarios para su adecuado funcionamiento Sitio Web utiliza los siguientes prestadores de servicios bajo sus correspondientes condiciones de privacidad:
            </p>

            <ul>
                <li>Google Analytics, para estadísticas. https://policies.google.com/privacy?hl=es</li>
            </ul>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Plugins sociales</h2>
        <div class="box-content-white">
            <p>
                En nuestro Sitio Web ofrecemos enlaces y servicios relacionados con diferentes redes sociales. Si el Usuario es miembro de una red social y hace clic sobre el correspondiente enlace, el proveedor de la red social podrá enlazar sus datos de perfil con la información de su visita al Sitio Web.
            </p>

            <p>
                Por tanto, el Usuario debe estar informado sobre las funciones y políticas sobre el tratamiento de sus datos personales de la respectiva red social. Tanto si accede a una de nuestras páginas
            </p>

            <p>
                El Usuario puedes acceder en todo momento a las políticas de privacidad de las diferentes redes sociales, así como configurar su perfil para garantizar su privacidad.
            </p>

            <ul>
                <li>
                    Facebook:
                    <a href="https://www.facebook.com/help/323540651073243/">
                        https://www.facebook.com/help/323540651073243/
                    </a>
                </li>
                <li>
                    Twitter:
                    <a href="https://twitter.com/privacy">
                        https://twitter.com/privacy
                    </a>
                </li>
                <li>
                    Youtube:
                    <a href="https://policies.google.com/privacy?hl=es&gl=es">
                        https://policies.google.com/privacy?hl=es&gl=es
                    </a>
                </li>
                <li>
                    Google Plus:
                    <a href="https://policies.google.com/privacy?hl=es&gl=es">
                        https://policies.google.com/privacy?hl=es&gl=es
                    </a>
                </li>
            </ul>
        </div>
    </section>

    <section class="row col-sm-12">
        <h2>Aceptación, consentimiento y revocabilidad</h2>
        <div class="box-content-white">
            <p>
                El Usuario declara haber sido informado de las presentes condiciones sobre protección de datos de carácter personal, aceptando y consintiendo el tratamiento de los mismos por parte de Sitio Web en la forma y para las finalidades indicadas en el Aviso Legal.
            </p>

            <p>
                En cualquier momento el Usuario podrá revocar sus datos, pero sin afectar a acciones ya realizadas en el pasado, es decir sin carácter retroactivo.
            </p>
        </div>
    </section>
</div>

views/site/userlocked.php
<?php
/**
 * Created by PhpStorm.
 * User: fryntiz
 * Date: 10/10/18
 * Time: 23:21
 */

use app\assets\UserLockedAsset;

/**
 * @author    Raúl Caro Pastorino
 * @link      https://fryntiz.es
 * @copyright Copyright (c) 2018 Raúl Caro Pastorino
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html
 **/

/* @var $this yii\web\View */

UserLockedAsset::register($this);

$this->title = 'Usuario Bloqueado';

?>
<div id="site-userlocked">
    <h1>Usuario Bloqueado</h1>
    <h2>Inicio de sesión no permitido para usuario bloqueado</h2>

    <p>
        Este usuario ha sido bloqueado.
    </p>

    <p class="alert-warning">
        Para cualquier consulta al respecto diríjase por favor a <?=
        Yii::getAlias('@adminEmail') ?>
    </p>
</div>