controllers/TorrentsController.php
<?php

namespace app\controllers;

use app\helpers\Access;
use app\helpers\Amazons3;
use app\helpers\Imageresize;
use app\helpers\Magnet2torrent;
use app\helpers\Roles;
use app\helpers\Security;
use app\models\Comentarios;
use app\models\Comment;
use app\models\Descargas;
use function array_combine;
use function array_map;
use function array_push;
use Bhutanio\BEncode\BEncode;
use DateTime;
use function fclose;
use function fopen;
use function fwrite;
use function implode;
use function isEmpty;
use function json_encode;
use PHP\BitTorrent\Decoder;
use PHP\BitTorrent\Encoder;
use function random_int;
use function sha1;
use function var_dump;
use Yii;
use app\models\Torrents;
use app\models\TorrentsSearch;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Categorias;
use app\models\Licencias;
use yii\web\UploadedFile;
use Devristo\Torrent\Torrent;
use yii2mod\editable\EditableAction;

/**
 * TorrentsController implements the CRUD actions for Torrents model.
 */
class TorrentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'delete', 'update'],
                'rules' => [
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['delete', 'update', 'eliminar'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            $id = Torrents::findOne($_REQUEST['id'])->usuario_id;
                            $isAdmin = Roles::isAdmin();
                            $isAutor = Access::isAutor($id);

                            if ($isAdmin || $isAutor) {
                                return true;
                            }

                            return false;
                        },
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'edit-page' => [
                'class' => EditableAction::className(),
                'modelClass' => Comentarios::className(),
                'forceCreate' => false
            ],
        ];
    }

    /**
     * Lists all Torrents models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TorrentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $query = Categorias::find()->select(['id', 'nombre'])->asArray()
            ->all();

        $categoriasId = [''];
        $categoriasNombres = ['Todas las Categorías'];

        foreach ($query as $ele) {
            array_push($categoriasId, $ele['id']);
            array_push($categoriasNombres, $ele['nombre']);
        }

        $categorias = array_combine($categoriasId, $categoriasNombres);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Displays a single Torrents model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Torrents model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (! Roles::canUpload()) {
            Yii::$app->session->setFlash('error', 'Has subido el límite de torrents diarios para tu rango actual');
            $this->redirect(['torrents/index']);
        }

        $model = new Torrents([
            'usuario_id' => Yii::$app->user->identity->id,
            'scenario' => Torrents::ESCENARIO_CREATE,

        ]);

        // En el caso de existir datos mediante POST los proceso
        if ($model->load(Yii::$app->request->post())) {
            $model->u_torrent = UploadedFile::getInstance($model, 'u_torrent');

            // Es obligatorio que haya un torrent para continuar
            if ($model->u_torrent !== null) {
                $torrent = Torrent::fromFile($model->u_torrent->tempName);
                $pieces = array_map(function($ele) {
                    return sha1($ele, false);
                }, $torrent->getPieces());
                $pieces = implode(',', $pieces);

                $length = [];
                $torrentArray = $torrent->toArray();
                if (!empty($torrentArray['info']['files'])) {
                    $files = $torrentArray['info']['files'];
                    foreach ($files as $file) {
                        $l = $file['length'];
                        array_push($length, $l);
                    }
                }

                $trackers = [];
                foreach ($torrent->getAnnounceList() as $tracker) {
                    array_push($trackers, $tracker[0]);
                }

                $model->n_piezas = $torrent->getNumPieces();
                $model->size_piezas = $torrent->getPieceSize();
                $model->torrentcreate_at = $torrent->getCreationDate()
                                            ->format('Y-m-d H:m:i');
                $model->size = $torrent->getSize(false);
                $model->hash = $torrent->getInfoHash(false);
                $model->archivos = implode(',', $torrent->getFiles());
                $model->archivos_hash = $pieces;
                $model->archivos_size = implode(',', $length);
                $model->trackers = implode(',', $trackers);
                $model->name = $torrent->getName();

                // Guardo imagen si existiera
                $model->u_img = UploadedFile::getInstance($model, 'u_img');
                if ($model->u_img !== null) {
                    $imgObject = new Imageresize($model->u_img);

                    // Subo Imagen a amazon
                    $imagenLocal = $imgObject->getRutaImagen();
                    $nombreAmazon = 'torrentimages/' . $imgObject->getNombre();
                    $amazon = new Amazons3();
                    $amazon->uploadImage(
                        $nombreAmazon,
                        $imagenLocal
                    );

                    $model->imagen = $amazon->getUrlImage($nombreAmazon);
                    $model->u_img = ''; // Deshabilito este atributo temporal.
                }

                if ($model->save()) {
                    //$rol = Yii::$app->user->identity->rol;
                    //$roles = Roles::allRoles();
                    Roles::subirRole();

                    return $this->redirect(['view', 'id' => $model->id]);
                }
            } else {
                Yii::$app->session->setFlash('error',
                                    'Es obligatorio el archivo torrent');
                $model->addError('u_torrent',
                    'Es obligatorio agregar un Torrent válido');
            }
        }

        $licencias = Licencias::getAll();
        $categorias = Categorias::getAll();

        return $this->render('create', [
            'model' => $model,
            'licencias' => $licencias,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Updates an existing Torrents model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $model->scenario = Torrents::ESCENARIO_UPDATE;

        $licencias = Licencias::getAll();
        $categorias = Categorias::getAll();

        return $this->render('update', [
            'model' => $model,
            'licencias' => $licencias,
            'categorias' => $categorias,
        ]);
    }

    /**
     * Convierte el enlace hash del magnet recibido en un archivo torrent
     * @param $hash
     */
    public function actionDescargar($id)
    {
        // Anoto una descarga para el torrent actual.
        $this->actionAnotardescarga($id);

        // Array con toda la información del torrent.
        $info = Magnet2torrent::generateTorrentInfo($id);

        $torrent = new Encoder();
        $torrent = $torrent->encodeDictionary($info);

        $torrentName = trim($info['info']['filename']).'.torrent';
        $rutaSave = 'uploads/'.$torrentName;

        $file = fopen($rutaSave, 'w+');
        $x = fwrite($file, $torrent);
        fclose($file);

        $this->redirect('/'.$rutaSave);
    }

    /**
     * Deletes an existing Torrents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Torrents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.

views/torrents/_form.php
<?php

use app\models\Torrents;use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Torrents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="torrents-form container">
    <?php $form = ActiveForm::begin(); ?>

    <div class="row col-sm-12">
        <div class="row col-sm-6">
            <?= $form->field($model, 'titulo')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
        </div>

        <div class="row col-sm-6">
            <?= $form->field($model, 'licencia_id')->dropDownList($licencias) ?>
            <?= $form->field($model, 'categoria_id')->dropDownList($categorias) ?>
        </div>
    </div>

    <div class="row col-sm-12">
        <?= $form->field($model, 'resumen')->textarea(['maxlength' => true]) ?>
    </div>

    <?php if ($model->scenario === Torrents::ESCENARIO_CREATE): ?>
    <div class="row col-sm-12">
        <?= $form->field($model, 'u_img')->fileInput() ?>
        <?= $form->field($model, 'u_torrent')->fileInput() ?>
    </div>
    <?php endif ?>

    <div class="row col-sm-12">
        <?= $form->field($model, 'descripcion')->textarea(['maxlength' => true]) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/torrents/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TorrentsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="torrents-search container">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'allfields')->label('Buscar:') ?>
        </div>

        <div class="col-sm-6">
            <?= $form->field($model, 'categoria_id')->dropDownList($categorias) ?>
        </div>
    </div>

    <div class="row text-center">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/torrents/create.php
<?php

use app\assets\TorrentsCreateAsset;
use yii\helpers\Html;

TorrentsCreateAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\Torrents */

$this->title = 'Subir Torrent';
$this->params['breadcrumbs'][] = ['label' => 'Torrents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="torrents-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'licencias' => $licencias,
        'categorias' => $categorias,
    ]) ?>

</div>

views/torrents/index.php
<?php

use app\helpers\Roles;
use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\TorrentsIndexAsset;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TorrentsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

// Registro assets para esta vista
TorrentsIndexAsset::register($this);

$this->title = 'Torrents';
$this->params['breadcrumbs'][] = $this->title;

$isAdmin = Roles::isAdmin();
$isGuest = Yii::$app->user->isGuest;
?>

<div class="torrents-index">
    <?php if (Roles::canUpload()): ?>
        <p>
            <?= Html::a('<i class="fa fa-upload"></i>
Añadir un torrent ', ['create'],
                ['class' => 'btn btn-primary']) ?>
        </p>
    <?php endif ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_search', [
        'model' => $searchModel,
        'categorias' => $categorias,
    ]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'id' => 'torrents-index-gridview',
        'class' => 'torrents-index-class',
        'summary' => false,  // Oculto total de elementos
        'showHeader' => false,
        //'showFooter' => false,
        'emptyCell' => 'N/D',
        'tableOptions' => [
            'class' => 'tablaTorrentsIndex',
        ],
        'pager' => [
            'class' => \kop\y2sp\ScrollPager::className(),
            'container' => '#torrents-index-gridview tbody',
            'item' => 'tr',
            'triggerOffset' => 1000,
            'negativeMargin' => 100,
            'delay'=>0,
            'spinnerSrc'=> '/'.yii::getAlias('@r_img').'/load-torrent.gif',
            'paginationSelector' => '.grid-view .pagination',
            'enabledExtensions'=> [
                \kop\y2sp\ScrollPager::EXTENSION_TRIGGER,
                \kop\y2sp\ScrollPager::EXTENSION_SPINNER,
                \kop\y2sp\ScrollPager::EXTENSION_NONE_LEFT,
                \kop\y2sp\ScrollPager::EXTENSION_PAGING
            ],
            //'triggerTemplate' => '<tr class="ias-trigger"><td  colspan="100%" style="text-align: center"><a style="cursor: pointer">{text}</a></td></tr>',
        ],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            //'id',
            [
                'attribute' => 'titulo',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-titulo'],
                //'headerOptions' => ['class' => 'titulo2'],
                'value' => function($model) {
                    return Html::a(Html::encode($model->titulo), [
                        Url::to('torrents/view'),
                        'id' => $model->id
                    ]);
                }
            ],
            [
                'attribute' => 'imagen',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-imagen'],
                'value' => function($model, $key, $index) {
                    $img = $model->imagen;

                    if ($model->imagen == '') {
                        $img = '/' . Yii::$app->request->baseUrl .
                            Yii::getAlias('@r_imgTorrent').'/default.png';
                    }

                    $img = '<img src="'.$img.'" alt="'.$model->titulo.'" />';
                    $link = Html::a($img, [
                        Url::to('torrents/view'),
                        'id' => $model->id
                    ]);

                    return $link;
                }
            ],
            [
                'attribute' => 'resumen',
                'contentOptions' => ['class' => 'tabla-resumen'],
            ],
            [
                'attribute' => 'licencia.tipo',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-licencia'],
                'value' => function($model, $key, $index) {
                    $img = $model->licencia->imagen;
                    $r_img = '/' . yii::getAlias('@r_imgLicencias').'/'.$img;

                    return '<a href="'.$model->licencia->url.'" target="_blank">'.
                        '<img src="'.$r_img.'" /></a>';
                }
            ],
            [
                'attribute' => 'categoria.nombre',
                'contentOptions' => ['class' => 'tabla-categoria'],
            ],
            [
                'attribute' => 'usuario.datos.nick',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-nick'],
                'value' => function($model) {
                    return Html::a(Html::encode($model->usuario->datos->nick), [
                        Url::to('usuarios/view'),
                        'id' => $model->usuario->datos_id
                    ]);
                }
            ],
            [
                'label' => 'Ficha del Torrent',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-vertorrent'],
                'value' => function($model) {
                    return Html::a('Ir a la ficha del Torrent', [
                        Url::to('torrents/view'),
                        'id' => $model->id
                    ]);
                }
            ],
            'size:shortSize',
            'created_at:date',
            [
                'label' => 'Subido el:',
                'format' => 'raw',
                'contentOptions' => ['class' => 'tabla-createdat'],
                'value' => function($model) {
                    return '<small class="torrentindexcreatedat">'.
                        'Subido el: '. Yii::$app->formatter
                            ->format($model->created_at, 'date') .
                        '</small>';
                }
            ],
        ],
    ]); ?>
    </div>
</div>

views/torrents/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Torrents */

$this->title = 'Modificar Torrent: ' . Html::encode($model->titulo);
$this->params['breadcrumbs'][] = ['label' => 'Torrents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->titulo, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="torrents-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'licencias' => $licencias,
        'categorias' => $categorias,
    ]) ?>

</div>

views/torrents/view.php
<?php

use app\helpers\Access;
use app\helpers\Magnet2torrent;
use app\helpers\Roles;
use yii\helpers\Html;
use app\assets\TorrentsViewAsset;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Torrents */

// Registro assets para esta vista
TorrentsViewAsset::register($this);

$this->title = Html::encode($model->titulo);
$this->params['breadcrumbs'][] = ['label' => 'Torrents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Variables
$isAdmin = Roles::isAdmin();
$isAutor = Access::isAutor($model->usuario_id);

function imagen($model) {
    $img = $model->imagen;

    if ($model->imagen == '') {
        $img = Yii::$app->request->baseUrl . '/' .
            Yii::getAlias('@r_imgTorrent').'/default.png';
    }

    return '<img src="'.$img.'" alt="'.$model->titulo.'" class="imagen" />';
}

function licencia($model) {
    $img = $model->licencia->imagen;
    $r_img = '/'.yii::getAlias('@r_imgLicencias').'/'.$img;

    return '<a href="'.$model->licencia->url.'" target="_blank">'.
        '<img src="'.$r_img.'" class="licencia" /></a>';
}

function size($model) {
    return 'Tamaño:<br />' . Yii::$app->formatter->asShortSize($model->size);
}

function uploader($model) {
    return 'Uploader:<br />' . Html::a(
        Html::encode($model->usuario->datos->nick), [
            Url::to('usuarios/view'),
            'id' => $model->usuario->datos_id
        ]
    );
}

function resumen($model) {
    return Html::encode($model->resumen);
}

function descargas($model) {
    return 'Descargado ' .
        '<span id="torrents-veces-descargado">' .
            $model->descargas .
        '</span>' .
        ' veces';
}

function categoria($model) {
    return 'Categoría: ' . $model->categoria->nombre;
}

function subido($model) {
    return 'Subido en ' . Yii::$app->formatter->asDatetime($model->created_at);
}

function contenido($model) {
    $archivos = explode(',', $model->archivos);
    $lista = '<ul class="listaArchivos">';
    foreach ($archivos as $archivo) {
        $lista .= '<li>'.$archivo.'</li>';
    }
    $lista .= '</ul>';

    return 'Contenido del torrent:<br />' . $lista;
}

function piezas($model) {
    return 'Piezas: ' . $model->n_piezas;
}

function piezasSize($model) {
    return 'Tamaño de Piezas: ' .
        Yii::$app->formatter->asShortSize($model->size_piezas);
}

function torrentCreacion($model) {
    return 'Creado en ' .
        Yii::$app->formatter->asDatetime($model->torrentcreate_at);
}

function descripcion($model) {
    return Html::encode($model->descripcion);
}

function magnet($model) {
    $magnet = 'magnet:?xt=urn:btih:' . $model->hash;
    $magnet .= '&dn='.urlencode(Html::encode($model->titulo));

    $trackersArray = Magnet2torrent::trackers();
    $trackers = '';
    foreach ($trackersArray as $tracker) {
        $trackers .= '&tr=' . urlencode(trim($tracker));
    }

    $r = '<span id="copymagnet" class="btn btn-warning">' .
            Html::img('/images/icons/magnet.png', [
                'alt' => 'Copy ' . Html::encode($model->titulo) .
                    ' magnet to clipboard',
                'title' => 'Copy ' . Html::encode($model->titulo) .
                    ' magnet to clipboard',
            ]) .

            'Copiar al portapapeles' .
        '</span>'
    ;

    $r .= Html::a('Abrir magnet con tu programa de torrents',
        Url::to($magnet.$trackers),
        [
            'title' => 'Descargar Magnet',
            'alt' => 'Descargar Magnet',
            'id' => 'magnet',
            'class' => 'btn btn-primary'
        ]
    );

    $r .= Html::a('Descargar Torrent',
        Url::to(['torrents/descargar',
            'id' => $model->id,
        ]),
        [
            'title' => 'Descargar '.Html::encode($model->titulo),
            'alt' => 'Descargar '.Html::encode($model->titulo),
            'id' => 'btn-torrent-download',
            'class' => 'btn btn-success col-sm-12',
            'data-torrent_id' => $model->id,
            'download'
        ]
    );

    return $r;
}

function puntuacion($model) {
    $puntosUsuarioActual = $model->misPuntos;

    return '<p>Puntuación total: ' .
            '<span id="torrent-puntos" 
                   data-mispuntos="'.$puntosUsuarioActual.'">' .
                $model->puntos .
            '</span>/10
        </p>' .

        '<div class="torrentRating rating" data-rating-max="10" 
              data-torrent="' . $model->id . '"></div>';
}

function reportar($model) {
    if (Yii::$app->user->isGuest) {
        return '';
    }

    if ($model->estareportado) {
        return 'Ya has reportado este torrent';
    }

    return '
    <span id="reportar-terminado">El torrent ha sido reportado.</span>
    <span id="btn-reportar" class="btn btn-link">Reportar Torrent</span>
    <div id="box-reportes" data-torrent="'.$model->id.'" class="form-group">
        Título: <input type="text" id="reportar-titulo" class="form-control" />
        <br />
        Motivo: <input type="text" id="reportar-descripcion" 
                       class="form-control" />
        <br />
        <div id="btn-enviar-reporte" class="btn btn-warning">Enviar Reporte</div>
    </div>
    ';
}
?>

<div class="torrents-view container">

    <h1><?= Html::encode($this->title) ?></h1>

    <div id="torrents-view-box">
        <div class="row">
            <div class="text-center col-sm-6">
                <?= imagen($model) ?>
            </div>

            <div class="col-sm-6">
                <div class="row">
                    <div class="col-sm-4 text-center">
                        <?= licencia($model) ?>
                    </div>
                    <div class="col-sm-4 text-center">
                        <?= size($model) ?>
                    </div>
                    <div class="col-sm-4 text-center">
                        <?= uploader($model) ?>
                    </div>
                </div>

                <div class="row">
                    <?= resumen($model) ?>
                </div>

                <div class="lista row">
                    <?= contenido($model) ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <?= descargas($model) ?>
            </div>

            <div class="col-sm-4">
                <?= categoria($model) ?>
            </div>

            <div class="col-sm-4">
                <?= subido($model) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <?= piezas($model) ?>
            </div>

            <div class="col-sm-4">
                <?= piezasSize($model) ?>
            </div>

            <div class="col-sm-4">
                <?= torrentCreacion($model) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <div class="row">
                    <div id="seeders" class="col-sm-12">
                        Cargando seeders...
                    </div>
                </div>

                <div class="row">
                    <div id="leechers" class="col-sm-12">
                        Cargando leechers...
                    </div>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="row">
                    <div class="col-sm-12">
                        <?= puntuacion($model) ?>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <?= reportar($model) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <?= descripcion($model) ?>
            </div>
        </div>

        <div class="row">
            <div class="magnet col-sm-12 text-center">
                <?= magnet($model) ?>
            </div>
        </div>

    </div>

    <?php if ($isAutor || $isAdmin): ?>
        <p>
            <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>

            <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => '¿Seguro que quieres eliminar este torrent?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    <?php endif ?>
</div>

<?= \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
    'commentView' => '@app/views/torrents/comentarios/_index.php',
    'maxLevel' => 4,
    'dataProviderConfig' => [
        'pagination' => [
            'pageSize' => 10
        ],
    ],
    'listViewConfig' => [
        'emptyText' => 'No hay comentarios',
    ],
]); ?>